### ISSUE TITLE
should aesmd be inside the container?

### ISSUE THREAD

**Issue by aep** [enclaive/enclaive-docker-nginx-sgx#1]
just started researching, so my understanding might be lacking still.
apparently aesmd is an application api gateway to /dev/sgx_provision

it is unversioned, doesn't add additional authentication or boundaries and seems to only be used by intel software (gramine) competing products just use the well defined kernel ABI 

 - https://www.kernel.org/doc/html/latest/x86/sgx.html
 - https://github.com/occlum/occlum#how-to-use

i'd suggest to move aesmd inside the container so docker run works out of the box on ubuntu 21.04

**Comment by sebastiangajek** [comment]
Cool idea. Definitely simplifies the deployment of condidential containers. We’re working on a new version of the gramineSDK and will try out your request.  

Apologies for brevity, message sent from my iPhone
